### PR TITLE
Implement x-global-options

### LINKED ISSUE #64: Add protobuf options
I would like to add arbitrary protobuf options to the generated file, namely `go_package`

```
option go_package = "myawesomepackage"
````

I can see two ways to achieve this:

# 1. Add an option to the command line.

```
openapi2proto -new_flag go_package=myawesomepackage ...
```
where `new_flag` would be replaced with the appropriate name (I was inclined to use `option`, but it was already taken)

# 2. Add an custom/extra field to the spec

I'm not an OpenAPI spec expert, but this being a rather free form text file, I'm sure there's room to add extra fields. Here I assume it's okay for us to add a top level field name `x-global-options`, but it could be anywhere

```yaml
openapi: 2.0
x-global-options:  # made this up
   go_package: myawesomepackage
...
```

I'd be willing to write up a patch if we can decide on a direction to go.

### PR DESCRIPTION
**Pull request by lestrrat**
fixes #64 

Accepts `x-global-options`, which generates the appropriate `option X = Y;` declarations in the proto file

### CODE REVIEW

**Comment by jprobinson** [comment]
Changes look good but once again, I have failed and brought these PRs in the wrong order.

Mind fixing the conflicts, @lestrrat? I'll bring this in pronto after that.

**Comment by lestrrat** [comment]
will take a look now

**Comment by lestrrat** [comment]
@jprobinson this is good to go. please merge #68 first :)

**Comment by jprobinson** [comment]
Thanks again, @lestrrat!

**Pull request merged**
