### PR TITLE
Check availability of remote file

### LINKED ISSUE #68: Check internet connectivity before running HTTP tests
Sometimes I work when there's connectivity, sometimes I don't have connection. It's really annoying for a test to fail just because of this. 

Would it be feasible to skip the tests that downloads specs from the internet when appropriate? I can see two possibilities:

a. Skip if there's no connectivity -- that is, if `http.Get(url)` fails, don't run the subsequent test.
b. Skip if the test if `-short` is specified. This at least gives you the option to skip if desired.

### PR DESCRIPTION
**Pull request by lestrrat**
This changes the tests to check for remote dependencies before
running those tests.

fixes #68

### CODE REVIEW

**Comment by jprobinson** [comment]
Sorry, looks like I should have merged these PRs in a different order, mind fixing the imports failures in the test?

```
./proto_test.go:12:2: imported and not used: "github.com/pmezard/go-difflib/difflib"
./proto_test.go:174:12: undefined: diffmatchpatch
```

**Comment by lestrrat** [comment]
Well, you're in luck: I was just about to go to bed, but I can certainly do that after I fix this :)

**Comment by lestrrat** [comment]
@jprobinson done. it's working on my local machine, please do your thing once travis passes :)

**Comment by lestrrat** [comment]
@jprobinson Oh wait. something looks weid

**Comment by jprobinson** [comment]
_thankyousir!_

**Pull request merged**
