### PR TITLE
don't panic on missing schema

### PR DESCRIPTION
**Pull request by tmc**

### CODE REVIEW

**Comment by jprobinson** [comment]
It sounds like this is a scenario when the endpoint has no response (right?). For that scenario, we should still include _something_ for the gRPC response as it's required. I'm thinking this case should be setup to use an `Empty` type, like we already do a few lines below your proposed changes: https://github.com/NYTimes/openapi2proto/blob/eb790836e6efb76313441f0f57fee87894b85485/openapi.go#L348

If you're willing, I would suggest changing this PR to:

1. Change the responseName to use `google.protobuf.Empty` when no 'Schema' has been included.
2. Change the `semantic_api` test fixture to include this style of empty response and make sure everything works as expected. (no proto object is created and the endpoint definition is using an `Empty` message)

**Comment by jprobinson** [comment]
Actually, now that I think about it, this may be resolved it we just change the 'Schema' attribute here to be a non-pointer: https://github.com/NYTimes/openapi2proto/blob/master/openapi.go#L45

Then, the string will just be considered empty and the `Empty` type will get used by the process.

**Comment by tmc** [comment]
that sounds reasonable

**Comment by jprobinson** [comment]
This has been resolved in PR #16. If no schema is supplied, a `google.protobuf.Empty` will be used.

**Pull request closed without merging**
